### ISSUE TITLE
[BUG]已經命名的生物還是會消失

### ISSUE THREAD

**Issue by lewis252310** [lewis252310/EDGE#10]
**#簡單描述你發現的錯誤**
*清楚、簡單、明瞭即可。*
已經命名的生物有時候依然會消失

**#發現問題時的動作**
*稍微詳細點的描述，比如步驟或當時情況。*
1. 蓋鐵人塔，命名殭屍
2. 去別的地方回來後殭屍不見了
3. 
......

**#預期效果**
*認為原本該是執行什麼動作？*
命名後的生物不應該會消失才對

**#截圖/照片**
*如果有截圖的話可以放上來，這樣更清楚。*

**#相關位置/資訊 (非必要，可自行添加)：**
 - 遊戲ID：All
 - 所在世界：All
 - 權限組：All
 - 物品/裝置相關：
 - 其他：

**#備註**
*如果你覺得上面的都不能描述，就寫這裡吧。*
可能跟Paper Sarver的設置有關?

**Comment by kamiya4047** [comment]
paper的問題
詳見 PaperMC/Paper#3157

**Comment by kamiya4047** [comment]
關
