### ISSUE TITLE
[BUG]後台錢包君訊息

### ISSUE THREAD

**Issue by kamiya4047** [lewis252310/EDGE#12]
**#簡單描述你發現的錯誤**
*清楚、簡單、明瞭即可。*
- 錢包君重置訊息應為發送給只有玩家自己看得到其他人看不到的訊息
所以後台不為玩家但還是有訊息產生
- 當伺服器延遲(小木斧過載etc.)訊息會重複多次造成洗屏

**#發現問題時的動作**
*稍微詳細點的描述，比如步驟或當時情況。*
1. 等重置時間
2. 
3. 
......

**#預期效果**
*認為原本該是執行什麼動作？*
後台不會出現錢包君餓了
被延遲訊息不會重複出現

**#截圖/照片**
*如果有截圖的話可以放上來，這樣更清楚。*
![Screenshot_20200819-005602.jpg](https://user-images.githubusercontent.com/58339640/90536595-3b659800-e1b7-11ea-8912-d1b4dabdf531.jpg)

**#相關位置/資訊 (非必要，可自行添加)：**
 - 遊戲ID：*
 - 所在世界：*
 - 權限組：*
 - 物品/裝置相關：*
 - 其他：*

**#備註**
*如果你覺得上面的都不能描述，就寫這裡吧。*

**Comment by lewis252310** [comment]
錢包君的訊息是用broadcast
所以大家都有訊息的，沒啥問題。
至於那個洗頻
只是every 1 minute誤植成every 5 second
跟小木斧沒關係

**Comment by kamiya4047** [comment]
了解
但我是指不該用broadcast應該用像
原本tellraw玩家之類的ouo

**Comment by lewis252310** [comment]
我是覺得這種整個伺服器統一又頻率不高的還是用broadcast吧
不然如果哪天又像上面那個誤植洗頻的問題
搞不好又要好久以後才會發現

**Comment by kamiya4047** [comment]
ok
改好了就關掉這串八

**Comment by kamiya4047** [comment]
關
