### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by leon10019** [lewis252310/EDGE#14]
/res tp blackhole 的[進階退還雪人助手]，除了[照日+]是退還成[時間記憶]以外，其他都是退還成[穿梭時鐘+]，甚至1個[穿梭時鐘+]可以換成32個[穿梭時鐘+]...

**Comment by lewis252310** [comment]
已解決
![1](https://user-images.githubusercontent.com/59472089/124352196-fd8c2980-dc39-11eb-9a53-f87e973f5f22.png)
