### ISSUE TITLE
[BUG] 隨機傳送不安全

### ISSUE THREAD

**Issue by lewis252310** [lewis252310/EDGE#2]
**簡單描述你發現的錯誤**
清楚、簡單、明瞭即可。
隨機傳送不安全

**發現問題時的動作**
稍微詳細點的描述，比如步驟或當時情況。
1. 隨機傳送 (/tpr)
2. 掉岩漿死掉或傳到海中央
3. 地獄使用會飛到天花板上
......

**預期效果**
認為原本該是執行什麼動作？
可開發/冒險的正常陸地
地獄天花板以下

**截圖/照片**
如果有截圖的話可以放上來，這樣更清楚。

**相關位置/資訊 (非必要，可自行添加)：**
 - 所在世界：主世界/地獄
 - 你的權限組：All
 - 物品/裝置相關：
 - 其他：

**備註**
如果你覺得上面的都不能描述，就寫這裡吧。

**Comment by NUTT1101** [comment]
考慮移除此插件或替換成腳本

**Comment by lewis252310** [comment]
- 補檔 : 2020/08/07
暫時禁用此插件
直到找到更好的方法

**Comment by kamiya4047** [comment]
換成使用BetterRTP
