### ISSUE TITLE
[BUG]贊助時間顯示不正確

### ISSUE THREAD

**Issue by lewis252310** [lewis252310/EDGE#7]
**#簡單描述你發現的錯誤**
*清楚、簡單、明瞭即可。*
無法正確的顯示贊助剩餘時間

**#發現問題時的動作**
*稍微詳細點的描述，比如步驟或當時情況。*
1. 無法正確顯示贊助時間，前台(佔位符)顯示的時間比後台(LuckPerms指令/網頁)少。
......

**#預期效果**
*認為原本該是執行什麼動作？*
完整正確的顯示剩餘時間

**#截圖/照片**
*如果有截圖的話可以放上來，這樣更清楚。*
藍框為正確時間，紅框為佔位符顯示時間
![2020-08-04_21 31 05](https://user-images.githubusercontent.com/59472089/89294779-f1e75a00-d69a-11ea-8793-a37bb84bfabd.png)

**#相關位置/資訊 (非必要，可自行添加)：**
 - 遊戲ID：ALL
 - 所在世界：ALL
 - 權限組：ALL
 - 物品/裝置相關：ALL
 - 其他：

**#備註**
*如果你覺得上面的都不能描述，就寫這裡吧。*

**Comment by lewis252310** [comment]
**問題點**
 - *PlaceholderAPI*底下附屬的 %luckperms_group_expiry_time_<groupname>% 無法正確顯示剩餘時間
 - lp user \<user\> info 才能正確顯示時間

**解決**
 - 暫時無法解決

**Comment by kamiya4047** [comment]
考慮一下RankGrant+
RankGrant+有時間檔寫剩下的時間
可是只能是/grant給的才有寫
plugins/RankGrantPlus/data.yml

我有找到可以parse yml檔的[文章](https://www.spigotmc.org/threads/reading-a-variable-from-a-yml-file-with-skript.231816/)看能不能幫上忙

搞不好lp也有時間檔

**Comment by lewis252310** [comment]
我不太確定RankGrant +的data.yml格式能不能讀取
但我會試試看

**Comment by lewis252310** [comment]
**問題點**
RankGrant+的data.yml是2個space
skript-yaml的yml寫入是4個space

**狀況**
仍在尋找解決辦法中...

**Comment by NUTT1101** [comment]
這是一個屬於papi插件的時間格式bug

目前已有外國玩家發現此bug並且回報給papi原作者了

****相關文章：https://github.com/lucko/LuckPerms/issues/2535****

期待下次更新修正:)

**Comment by kamiya4047** [comment]
等下次PlaceHolderAPI更新應該會解決
那就先關了喔
