### ISSUE TITLE
[BUG]傳送時吃飛行能量

### ISSUE THREAD

**Issue by hank537** [lewis252310/EDGE#9]
當在空中傳送時飛行能量會被吃光

**Comment by NUTT1101** [comment]
考慮改用自寫腳本代替cmi飛行秒數購買

**Comment by lewis252310** [comment]
考慮移除飛行功能(已有領地內無限飛行)
若此則需要補償新增其他功能
**弊**
 - 玩家損失飛行權益

**利**
 - 伺服器減少檢查飛行模式的數量

**Comment by kamiya4047** [comment]
config可以解決只是會變用秒為單位花費而不是幾格方塊

cmi/config.yml 第1070到1072行
```yaml
# If this is set above 0, then player will loose defined amount of charges each second they are flying instead of traveled blocks
# Set to 0 to disable, which will deduct charges for traveled blocks
  DeductOnlyForTime: 0.0

**Comment by kamiya4047** [comment]
不要覺得修不了就加上標籤
除非原插件作者自己有說為止

**Comment by lewis252310** [comment]
經過測試，似乎並沒有這樣的BUG
判定非系統錯誤

**備註**
 - 格式無效，資訊不足
 - 無法判斷綜合情況(世界/傳送類型/飛行能量情況)
 - 暫時關閉
